server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/prime_db
    username: postgres
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
